import type { Theme } from "@mui/material"
import {
  getAccordion,
  getAppBar,
  getButtons,
  getCards,
  getChips,
  getAvatars,
  getDialogs,
  getDividers,
  getDrawers,
  getMenus,
  getForms,
  getSelects,
  getCheckboxes,
  getRadios,
  getSwitchToggle,
  getTabs,
  getTooltips,
  getToggleButtons,
  getTimeline,
  getStepper,
  getProgress,
  getPagination,
  getIcon,
  getGrid,
  getDataGrid,
  getContainer,
  getTreeView,
  getBreadcrumbs,
} from "../components/index"

export const getComponents = (theme: Theme) => {
  return {
    components: {
      ...getAccordion(theme),
      ...getAppBar(theme),
      ...getButtons(theme),
      ...getCards(theme),
      ...getChips(theme),
      ...getAvatars(theme),
      ...getDialogs(theme),
      ...getDividers(theme),
      ...getDrawers(theme),
      ...getMenus(theme),
      ...getForms(theme),
      ...getSelects(theme),
      ...getCheckboxes(theme),
      ...getRadios(theme),
      ...getSwitchToggle(theme),
      ...getTabs(theme),
      ...getTooltips(theme),
      ...getToggleButtons(theme),
      ...getTimeline(theme),
      ...getStepper(theme),
      ...getProgress(theme),
      ...getPagination(theme),
      ...getIcon(),
      ...getGrid(),
      ...getDataGrid(theme),
      ...getContainer(),
      ...getTreeView(theme),
      ...getBreadcrumbs(theme)
    },
  }
}
