name: Publish NPM Packages

on:
  push:
    branches:
      - ActionFix 

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.9.0' 
        registry-url: 'https://npm.pkg.github.com'
        scope: '@dataflor-ag' 
  
    - name: Install dependencies
      run: npm ci
        
    - name: Build Icons
      run: cd packages/df-ui-icons && npm run build && cd ../..

    - name: Build Icons
      run: cd packages/df-ui-icon-wrapper && npm run build && cd ../..

    - name: lerna publish --concurrency 1
      run: npx lerna publish from-package --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PRIVATE_NPM_PUBLISH }}
