name: Publish NPM Packages

on:
  push:
    branches:
      - main 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18' 
        registry-url: 'https://npm.pkg.github.com'
        scope: '@dataflor-ag' 

    - name: Install dependencies
      run: npm ci

    - name: Publish to GitHub Packages
      run: npx lerna publish from-git --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PRIVATE_NPM_PUBLISH }}
